### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by fee1-dead** [x4e/rs-jvm-bindings#2]
Please share the difference between this library and [jni-rs](https://github.com/jni-rs/jni-rs).

**Comment by x4e** [comment]
jni-rs is a high level wrapper, rs-jvm-bindings is a low level direct ffi interface.

If you meant jni-sys, the crate that jni-rs depends on, that only implements bindings for jni.h, while this crate covers 
* classfile_constants
* jawt
* jdwp
* jmm
* jni
* jvm
* jvmti
* jvmticmlr

If your usecase only requires JNI then feel free to use jni-rs or jni-sys.

**Comment by fee1-dead** [comment]
Put this in the README instead of putting it here?

**Comment by x4e** [comment]
why?

**Comment by fee1-dead** [comment]
You think the current description is good? Just "JVM bindings for rust"?

**Comment by x4e** [comment]
It clearly explains that this crate contains bindings for the JVM and all its interfaces.

Perhaps if you'd read that you wouldn't have mixed this crate up with a JNI crate?

**Comment by fee1-dead** [comment]
Does it cover ALL JVM exports?

**Comment by x4e** [comment]
All documented exports yes (even internal ones, such as JVM/JMM)

**Comment by fee1-dead** [comment]
I think you should still list java modules that this library provides bindings for in README.

**Comment by x4e** [comment]
Good idea
